### ISSUE TITLE
have trouble when installing the package on M1 mac

### ISSUE THREAD

**Issue by zheng017** [mqbssppe/multinomialLogitMix#1]
I have trouble when installing this package on M1 MacBook Air. I download the files and try to use the following command to install the package:
```r
install.packages("~/Codes/R/multinomialLogitMix-main/version_1.0/multinomialLogitMix_1.0.tar.gz", repos = NULL, type = "source")
```

I get the errors in the following:
```r
* installing *source* package ‘multinomialLogitMix’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c multinomialLogitMix.cpp -o multinomialLogitMix.o
multinomialLogitMix.cpp:44:18: warning: variable 'npars' set but not used [-Wunused-but-set-variable]
        int k, i, r, d, npars, acceptance;
                        ^
1 warning generated.
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o multinomialLogitMix.so RcppExports.o multinomialLogitMix.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [multinomialLogitMix.so] Error 1
ERROR: compilation failed for package ‘multinomialLogitMix’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/multinomialLogitMix’
Warning in install.packages :
  installation of package ‘/Users/zhengzhi/Codes/R/multinomialLogitMix-main/version_1.0/multinomialLogitMix_1.0.tar.gz’ had non-zero exit status
```

The first warning occurs at the 44 line of `multinomialLogitMix.cpp` as the variable "npars" are not used except line 58. This can be fixed easily.

However, I fail to solve the errors about "gfortran" as the error message shows. I have already installed gfortran in my computer and the location is :
```bash
(base) zhengzhi@zhengzhideMacBook-Air bin % which gfortran
/usr/local/bin/gfortran
```

Look forward to your reply.

**Comment by mqbssppe** [comment]
Thank you for mentioning this, however the only way I could test this now is through Rhub.
So I tested the package using the Rhub library in a Mac platform. 

`
 check("multinomialLogitMix/version_1.0/multinomialLogitMix_1.0.tar.gz", platform = 'macos-highsierra-release')
`
It seems that the issue is not reproducible and it might be specific to your machine.  The package is installed successfully (status: OK).

![rhub](https://user-images.githubusercontent.com/3490226/182096334-f85e9cde-f88e-4a87-a496-cc659b94d9cc.jpg)

**Comment by zheng017** [comment]
> Thank you for mentioning this, however the only way I could test this now is through Rhub. So I tested the package using the Rhub library in a Mac platform.
> 
> `check("multinomialLogitMix/version_1.0/multinomialLogitMix_1.0.tar.gz", platform = 'macos-highsierra-release')` It seems that the issue is not reproducible and it might be specific to your machine. The package is installed successfully (status: OK).
> 
> ![rhub](https://user-images.githubusercontent.com/3490226/182096334-f85e9cde-f88e-4a87-a496-cc659b94d9cc.jpg)

Thanks for your reply!

I have already fixed this problem by uninstalling the previous version of gfortran and install a new version following this url:
[https://mac.r-project.org/tools/](url). And it solved my problem. If people have similar issues, this solution may be helpful.
